import turtle
class emoji:
    def __init__(self):
        self.pen = turtle.Turtle()
        self.size = 6
        self.pen.speed(10)
    def wilted_rose(self):
            color1,color2 = self.pen.color()
            size1 = self.pen.pensize()
            self.pen.color("red")
            self.pen.penup()
            self.pen.forward(4*self.size)
            self.pen.right(90)
            self.pen.pendown()
            self.pen.begin_fill()
            self.pen.circle(3.5*self.size,100)
            self.pen.left(40)
            self.pen.forward(1*self.size)
            self.pen.left(40)
            self.pen.circle(3*self.size,140)
            self.pen.end_fill()
            self.pen.right(90)
            self.pen.color("green")
            self.pen.pensize(5)
            self.pen.circle(2*self.size,130)
            self.pen.left(40)
            self.pen.forward(1.5*self.size)
            self.pen.left(150)
            self.pen.circle(0.8*self.size,200)
            self.pen.circle(0.8*self.size,-200)
            self.pen.right(150)
            self.pen.forward(self.size)
            self.pen.right(40)
            self.pen.right(40)
            self.pen.circle(self.size,-180)
            self.pen.circle(self.size,180)
            self.pen.left(40)
            self.pen.forward(4*self.size)
            self.pen.penup()
            self.pen.left(90)
            self.pen.forward(5*self.size)
            self.pen.left(90)
            self.pen.forward(7.6*self.size)
            self.pen.right(90)
            self.pen.forward(3*self.size)
            self.pen.pendown()
            self.pen.color(color1)
            self.pen.pensize(size1)
a = emoji()
a.wilted_rose()
